
version: '1'
services:

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    expose:
      - 5432
    ports:
      - '5432:5432'
    # volumes:
    #   - /data/example/mysql:/var/lib/mysql
    restart: always
    networks:
      - backend

  realtime_d3_api:
    container_name: realtime_d3_api
    depends_on:
      - db
    build:
      context: ./RealTime_D3
      dockerfile: Dockerfile
    environment:
        - Logging__Loglevel__Default=Debug
        - Logging__Loglevel__Microsoft.AspNetCore=Debug
        - ASPNETCORE_URLS=http://+:80
    ports: 
      - '8080:80'
      - '8081:443'
    restart: always
    links:
      - db

    networks:
      - backend
      - frontend

  log_generator:
    container_name: log_generator
    depends_on:
      - realtime_d3_api
    build:
      context: ./Log_generator
      dockerfile: Dockerfile
    restart: always
    links:
      - realtime_d3_api
    networks:
      - frontend   
  realtime_d3_client:
    container_name: realtime_d3_client
    depends_on:
      - realtime_d3_api
    build:
      context: ./WASM_RealTime_D3
      dockerfile: Dockerfile
    ports: 
      - '8088:80'
    restart: always
    links:
      - realtime_d3_api
    networks:
      - frontend 
  
networks:
  backend:
  frontend:


